blog/urls.py
from django.urls import path
from .views import mis_posts, post_detail
#esta variable de namespace es para llamasr las urls de mi blog
app_name='blog'
urlpatterns=[
    #estas son las rutas de mi blog, las escribo aqui
    #y con la funcion de include de urls principal 
    #no necesito redenderizar mas
    path('',mis_posts,name='posts'),
    #aqui utilizo una convercion de tipo '<>' que arroja un parametro entero, y llama a uma funcion vista
    #este parametro se le pasara a la vista funcion post_detail
    path('<int:post_id>', post_detail, name='post_detail')
]

django_portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from portafolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    #cuando visite la app blog redenderice de la carpeta blog el archivo urls
    #y en el archivo urls esta mi views funcion redenderizado de mis_posts
    path('blog/',include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime 
# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    imagen=models.ImageField(upload_to='blog/images/')
    #si no agrega fecha el datetime me pone la del momento
    date=models.DateField(datetime.date.today)
    objects=models.Manager()

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=200)
    image = ImageField(upload_to="portafolio/images/")
    url = URLField(blank=True)
    objects=models.Manager()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.
def mis_posts(request):
    plasmar_en_html=Post.objects.all()
    return render(request, 'posts.html', {'post':plasmar_en_html})

def post_detail(request, post_id):
    #utilizo la funcion get_object_or_404 le paso el modelo y si no esta en la base de datos
    #el pk, osea el primarykey lance un error de no found
    existe_post=get_object_or_404(Post,pk=post_id)
    #esta funcion vista redenderiza la vista html y se le pasa el parametro post_id
    #que viene de el archivo url de la app blog
    return render(request, 'posts_detail.html', {'detail':existe_post} )

portafolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.d

def home(request):
    mis_proyectos= Project.objects.all()
    return render(request, 'home.html',{'proyectos':mis_proyectos})



#42:28 reanudar video

blog/templates/posts.html
{%extends 'layout.html'%}
{%block content%}
    <h1>mis publicaciones, no te lo pierdas</h1>
    {%for pos in post%}
   <div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{pos.imagen.url}}"class="img-fluid" alt="imagen cargando">
            </div>
            <div class="col-9">
                        
                <h1>{{pos.title}}</h1>
                <!--para formatear la fecha a pos.date, le paso date-->
                <h2>{{pos.date| date:' l F o '}}</h2>
                <!--si quiero en mi post principal restringi o limitar lo que se muestra, para que la principal,
                no se muestre todo, solo lo que quiero que se vea es con truncatechars:"la cantidad que quiero"
                en este caso la funcion stripstags estripa las etiquetas para que en el html no se vea '<>'-->
                <p>{{pos.description|striptags| truncatechars:200 }}</p>
                
                <!--aqui se hace el llamado a una url, que inicia como blog(variable de space en blog/url: app_name) 
                    y se le pasa la funcion post_detail, esta funcion requiere de un parametro, se lo pasamos: pos.id
                -->
                <a href="{% url 'blog:post_detail' pos.id %}" class="btn btn-primary">{{pos.title}}</a>
        
            </div>
        </div>

    </div>
   </div>

    {%endfor%}
{%endblock%}

blog/templates/posts_detail.html
{%extends 'layout.html'%}
{%block content%}
   <div class="text-center">
    <h1>Post</h1>

    <h1>{{detail.title}}</h1>
    <h2 class="my-2 h5 text-muted">{{detail.date|date:'l F o'}}</h2>
    <img src="{{detail.imagen.url}}" class="img-fluid" alt="">
    <div class="my-4">
        <p >{{detail.description}}</p>
    </div>
   </div>
    
   

{%endblock%}

portafolio/templates/home.html
{%extends 'layout.html'%}
{% load static %}




{%block content%}

<header class="row">
    <div class=" item-expand col-md-4">
        <img src="{% static 'portafolio/foton.jpg'%}" width="400" height="400">
    </div>
    <div class="col-md-6">
        <h1>Soy <strong>Maiker Stanley Cañon Garces</strong> </h1>
        <h3>Soy desarrollador junior python</h3>
        <p>Soy estudiante de septimo semestre de ingenieria de software, en la mejor universidad del sur de colombia "USCO ". Trabajo con python, Django, bootstrap, React, MongoDB, SQL, HTML Y css. Cada dia sigo aprendiendo</p>
        <a href="https://www.linkedin.com/in/maiker-ca%C3%B1on-9785a8283" class="btn btn-success" target="_blank">Linkedin</a>
    </div>
    
</header>
   <div class="row my-4 text-center" class="text-light">
        
        <h1>Aqui los proyectos</h1>
        <p>Disfruta de la maravilla de la tecnología</p>
        <!-- mostrar el titulo de los proyectos -->

        {%for i in proyectos%}
        <div class="col-md-4 p-4">
            <div class="card h-100 card-project " >
                <div class="card-body ">
                    <h3>{{i.title}}</h3><p>{{i.description}}</p>
                    <img src="{{i.image.url}} " class="img-fluid border" > <!--la clase de boostrap no permite que las imagenes se salgan de las tarjetas-->
                    
                    {%if i.url%}
                
                        <a href="{{i.url}}" class="btn btn-primary img-fluid  my-2">{{i.url}}</a>
                        
        
                    {%endif%}
                </div>
            </div>
        </div>
        {%endfor%}
   </div>

{%endblock%}

portafolio/templates/layout.html
{% load static %} <!--static es para cargar de la carpeta static lo que he cargado en ella, img . pdf etc-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
    <title>Django Portafolio</title>
    <link  href="{% static 'portafolio/main.css' %}" rel="stylesheet">
</head>
<body class="text-light">
    {%include 'partials/navbar.html'%}
    
    <!--aqui creo una plantilla para importarla en todas mis vistas
    una sola porcion de codigo para todas las vistas-->
    <div class="container p-4 " >
        {%block content%}

        {%endblock%}

    </div>

    <footer>Footer</footer>
</body>
</html>

portafolio/templates/partials/navbar.html
{% load static%}
<nav class="navbar navbar-expand bg-success">
    <div class="container"> <!--si le quito el fluid centra los textos-->
      <a class="navbar-brand text-white fw-bold fst-italic" href="/">MAIKER CAÑON</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ms-auto">
          
            <li class="nav-item ">
                <a class="nav-link" href="{%url 'blog:posts'%}">Blog</a>
            </li> 
            <li class="nav-item d-flex aling-tems-center">
                <a class="btn btn-primary text-dark " href="{%static 'portafolio/cvcv.pdf' %}" target="_blank">Descarga CV</a>
            </li>
        </ul>
      </div>
    </div>
  </nav>
 